name: Deploy Next.js ke VPS

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy ke VPS pakai SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /usr/src/www/first-cicd-nextjs
            git pull origin main
            npm install --legacy-peer-deps
            npm run build
            pm2 restart first-cicd-nextjs 
